### PR TITLE
Implemented infixToPostfix

### PR DESCRIPTION
**Pull request by dmadams**

### CODE REVIEW

**Comment by JackTFB** [comment]
So one quick check, I tried running the code on my computer, and it does generate the text files, but it doesn't convert the Infix to Postfix or even output anything into the program.  Is it different on your end?

**Comment by dmadams** [comment]
Did you provide any command line arguments? It should just create blank files when no arguments are provided.

**Comment by JackTFB** [comment]
All I did was simply run the script, and then input the expression in quotations in the console.  I didn't think there were any extra arguments needed

**Comment by dmadams** [comment]
It doesn’t listen for input from the command line. It simply uses arguments provided in the same line. 
Should be something like:
`% Calculator “1+1” “2 * 2”`
Not:
`% Calculator`
`% “1+1”`
`% “2 * 2”`

Though, that would be a good improvement and not hard for me to add.

**Comment by JackTFB** [comment]
Ok I figured out how to use it.  We could improve it on that end, or just leave some instructions included with the script for the professor if we want to save some time.  I'm going to go ahead and work on Postfix to Expression Method.  Sorry it took me a bit.  Work and stuff XD.  Just let me know what you decide to do, and I'll merge the pull request.

**Comment by JackTFB** [comment]
I'm gonna merge the pull request and grind out my section today.  If I have free time, I'll also try to rewrite the code to support console inputs instead of command line arguments.  If you want to try to tackle it as well while I work on my method, feel free to.

**Pull request merged**
